name: full-check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: first_build
      run: |
           ./autogen.sh
           ./configure --with-generic-jconfig
           make
           make clean
           make
           sudo make install
           sudo make uninstall
           make distclean
    - name: second_build
      run: |
           ./autogen.sh
           ./configure --with-generic-jconfig
           make
           sudo make install
    - name: run_program
      run: |
           outguess 2>&1 | egrep -A 20 OutGuess
           outguess -h 2>&1 | egrep -A 20 OutGuess
    - name: test_outguess
      run: |
           sudo make uninstall
           make check
